### ISSUE TITLE
Bearer Authentication

### ISSUE THREAD

**Issue by denisenkodmitry** [nativesoftcom/nativerest#1]
It would be great if NativeRest supported Bearer as an authentication method to use.

**Comment by devulex** [comment]
👋 Dmitry, thanks for opening your first issue! In the current version, you can manually specify the Authentication header. In the next release 0.9.0 I will add the Bearer authentication method 👌.

**Comment by devulex** [comment]
Auth methods has been implemented in release 0.9.0.
Now you can select Basic or Bearer authorization method.

![nativerest-basic-auth](https://user-images.githubusercontent.com/24734235/220864048-50219b04-4f07-488d-94fe-9ce8ba4f167b.png)
The new release is available here [nativesoft.com/nativerest](https://nativesoft.com/nativerest)
