### ISSUE TITLE
Import data from Postman

### ISSUE THREAD

**Issue by VadimSVG** [nativesoftcom/nativerest#2]
I want to migrate my requests and collections to NativeRest. Please add import of collections and environments from Postman.

**Comment by nativesoftcom** [comment]
👋 Vadim, thanks for opening your first issue! I agree with you completely. This is an important feature for many users migrate from other REST-clients. In the next release 1.0.0 I will add import data from Postman and Insomnia 👌.

**Comment by devulex** [comment]
👋 Vadim, thanks for opening your first issue! I agree with you completely. This is an important feature for many users migrate from other REST-clients. In the next release 1.0.0 I will add import data from Postman and Insomnia 👌.

**Comment by devulex** [comment]
Import collections has been implemented in release 1.0.0.
You can choose the file format Postman or Insomnia.
![nativerest-import-data](https://github.com/nativesoftcom/nativerest/assets/24734235/e2f406f9-a4ed-4775-9e66-97a593a4a505)
The new release is available here nativesoft.com/nativerest
