### ISSUE TITLE
Sending binary files

### ISSUE THREAD

**Issue by taraska** [nativesoftcom/nativerest#3]
Please add the option to send binary files.

**Comment by devulex** [comment]
👋 [taraska](https://github.com/taraska), thanks for opening your first issue! In the next release 1.1.0 I will add sending binary files.

**Comment by devulex** [comment]
Ability to send binary files has been implemented in release 1.7.0.
You can select the file on your PC. The form displays the file size and MIME-type.

![image](https://github.com/nativesoftcom/nativerest/assets/24734235/2944c87f-7419-4589-85bd-cc2cd382827a)

The new release is available here [nativesoft.com/nativerest](https://nativesoft.com/nativerest)
