### ISSUE TITLE
Bearer token field too short

### ISSUE THREAD

**Issue by ArsProgramma-private** [nativesoftcom/nativerest#4]
I have a bearer token that is created in a C#-RestApi like this:

`builder.Services.AddAuthentication(opt =>
{
    opt.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    opt.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    opt.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
}).AddJwtBearer(opt =>
{
    opt.IncludeErrorDetails = true;
    opt.SaveToken = true;
    opt.RequireHttpsMetadata = requireHttpsMetadata;
    opt.TokenValidationParameters = new TokenValidationParameters
    {
        ClockSkew = TimeSpan.Zero,
        ValidateIssuer = true,
        ValidateAudience = true,
        ValidateLifetime = true,
        ValidateIssuerSigningKey = true,
        ValidAudience = validAudience,
        ValidIssuer = validIssuer,
        ValidAlgorithms = new[] { SecurityAlgorithms.HmacSha256 },
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(securityKey))
    };
});`

The resulting Bearer is about 671 chars long.

When I insert this into the Bearer-Authentication field the max-length of that field cuts of that bearer, rendering this totally useless for my API.

**Comment by devulex** [comment]
👋 @ArsProgramma-private, thank you for the detailed description of the problem. In version 1.9.0 the maximum token length has been increased to 8192 characters. The new release is available here [nativesoft.com/nativerest](https://nativesoft.com/nativerest).
