### ISSUE TITLE
Traditional Chinese translation issues

### ISSUE THREAD

**Issue by bestpika** [nativesoftcom/nativerest#5]
身體 => This is usually not translated, just keep Body.
授權 => 驗證
安慰 => 控制台
回收站 => 回收桶
導入數據 => 匯入資料
匯出數據 => 匯出資料
![image](https://github.com/user-attachments/assets/e303522c-2225-4144-bb5a-a00396105620)

基本的 => 基本
要求 => 請求
代理人 => 代理伺服器
應用程式擴充 => 應用程式縮放
![image](https://github.com/user-attachments/assets/cc71de23-9413-48af-ac8f-816cc6ebda64)

縮排尺寸 => 縮排大小
自動關閉報價 => 自動關閉引號
![image](https://github.com/user-attachments/assets/0e8f204c-fd26-47d7-baf7-d565554d1541)

請求超時 => 請求逾時
![image](https://github.com/user-attachments/assets/010a4190-a92f-43e6-bc99-621f7957a991)

旁路 => 繞過 or do not translate, retain Bypass
![image](https://github.com/user-attachments/assets/d51f0c78-94e4-49cb-bbdb-82b8a15b62d8)

快速方式 => 快速鍵
![image](https://github.com/user-attachments/assets/05fe6cea-ce7c-4179-ba2f-10ba292e647a)

姓名 => 名稱
貯存 => 儲存
雲 => 雲端
![image](https://github.com/user-attachments/assets/4821b5b1-144d-43f2-8c48-5556576dd083)

回收站 => 回收桶
![image](https://github.com/user-attachments/assets/9b7d9267-a8f4-42e0-8d02-d6b2c93ba0ce)

Currently, I see that these translations have issues.
If you can provide the string file, I can complete the translation and then give it back to you.

**Comment by devulex** [comment]
@bestpika, thank you for describing in detail what needs to be fixed. 🛠 I have already corrected the phrases. The next version 2.1.5 should appear on July 21st. Write if you notice any other problems or have any suggestions. 🚀

**Comment by devulex** [comment]
👋 @bestpika, phrases have been corrected in release 2.1.5.
The new release is available here [nativesoft.com/nativerest](https://nativesoft.com/nativerest).
